package com.real.doctor.realdoc.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.real.doctor.realdoc.model.PrefBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PREF_BEAN".
*/
public class PrefBeanDao extends AbstractDao<PrefBean, String> {

    public static final String TABLENAME = "PREF_BEAN";

    /**
     * Properties of entity PrefBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Disabled_groups = new Property(0, String.class, "disabled_groups", true, "DISABLED_GROUPS");
        public final static Property Disabled_ids = new Property(1, String.class, "disabled_ids", false, "DISABLED_IDS");
    }


    public PrefBeanDao(DaoConfig config) {
        super(config);
    }
    
    public PrefBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PREF_BEAN\" (" + //
                "\"DISABLED_GROUPS\" TEXT PRIMARY KEY NOT NULL ," + // 0: disabled_groups
                "\"DISABLED_IDS\" TEXT);"); // 1: disabled_ids
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PREF_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PrefBean entity) {
        stmt.clearBindings();
 
        String disabled_groups = entity.getDisabled_groups();
        if (disabled_groups != null) {
            stmt.bindString(1, disabled_groups);
        }
 
        String disabled_ids = entity.getDisabled_ids();
        if (disabled_ids != null) {
            stmt.bindString(2, disabled_ids);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PrefBean entity) {
        stmt.clearBindings();
 
        String disabled_groups = entity.getDisabled_groups();
        if (disabled_groups != null) {
            stmt.bindString(1, disabled_groups);
        }
 
        String disabled_ids = entity.getDisabled_ids();
        if (disabled_ids != null) {
            stmt.bindString(2, disabled_ids);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public PrefBean readEntity(Cursor cursor, int offset) {
        PrefBean entity = new PrefBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // disabled_groups
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // disabled_ids
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PrefBean entity, int offset) {
        entity.setDisabled_groups(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDisabled_ids(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(PrefBean entity, long rowId) {
        return entity.getDisabled_groups();
    }
    
    @Override
    public String getKey(PrefBean entity) {
        if(entity != null) {
            return entity.getDisabled_groups();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PrefBean entity) {
        return entity.getDisabled_groups() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
